const fs=require('fs'),path=require('path');const {createCanvas,loadImage}=require('@napi-rs/canvas');
const out=path.resolve(__dirname,'..'),W=1254,H=700,P=28,cycle=40,step=cycle*P/8;
const pivot=[600,390],helm=[659,385],muzzle=[1115,400];
const rotate=(p,o,a)=>[o[0]+(p[0]-o[0])*Math.cos(a)-(p[1]-o[1])*Math.sin(a),o[1]+(p[0]-o[0])*Math.sin(a)+(p[1]-o[1])*Math.cos(a)];
function foot(i,side){const q=(i+(side==='right'?4:0))%8;const t=(q-4)/4;return[q<=4?870-q*step:310+560*t*t*(3-2*t),side==='left'?265:530];}
function segment(c,im,r,a,b,width){c.save();c.translate(...a);c.rotate(Math.atan2(b[1]-a[1],b[0]-a[0]));c.drawImage(im,...r,-5,-width/2,Math.hypot(b[0]-a[0],b[1]-a[1])+10,width);c.restore();}
function leg(c,im,i,side,ang){const f=foot(i,side),sgn=side==='left'?-1:1,hip=rotate([640,390+sgn*42],[640,390],ang),ankle=[f[0]-28,f[1]],dx=ankle[0]-hip[0],dy=ankle[1]-hip[1],d=Math.hypot(dx,dy);const knee=[(hip[0]+ankle[0])/2-sgn*dy/d*18,(hip[1]+ankle[1])/2+sgn*dx/d*18],off=side==='left'?0:550;segment(c,im,[140,370+off,460,205],hip,knee,68);segment(c,im,[580,400+off,425,175],knee,ankle,58);c.drawImage(im,990,400+off,235,170,f[0]-48,f[1]-30,96,60);return hip;}
function bbox(cv,filter=()=>true){let b=[W,H,0,0],d=cv.getContext('2d').getImageData(0,0,W,H).data;for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(d[(y*W+x)*4+3]>=32&&filter(x,y)){b=[Math.min(b[0],x),Math.min(b[1],y),Math.max(b[2],x+1),Math.max(b[3],y+1)];}return b;}
(async()=>{const base=await loadImage(path.join(out,'source/reference.png')),limbs=await loadImage(path.join(out,'source/legs.png'));let layers=createCanvas(W*4,H*6),lc=layers.getContext('2d'),atlas=createCanvas(W*4,H*2),ac=atlas.getContext('2d'),frames={},measure=[],renders=[],legRenders=[];
for(let i=0;i<8;i++){const phase=Math.cos(i*Math.PI/4),hipDeg=8*phase,shoulderDeg=-3.2*phase,angle=shoulderDeg*Math.PI/180;const cvs=['leg-left','leg-right','upper'].map(()=>createCanvas(W,H));leg(cvs[0].getContext('2d'),limbs,i,'left',hipDeg*Math.PI/180);leg(cvs[1].getContext('2d'),limbs,i,'right',hipDeg*Math.PI/180);let uc=cvs[2].getContext('2d');uc.translate(...helm);uc.rotate(angle);uc.drawImage(base,0,0,W,H,-helm[0],-helm[1],W,H);
let cv=createCanvas(W,H),c=cv.getContext('2d'),legs=createCanvas(W,H);cvs.forEach((v,j)=>{c.drawImage(v,0,0);if(j<2)legs.getContext('2d').drawImage(v,0,0);lc.drawImage(v,(i%4)*W,(Math.floor(i/4)*3+j)*H)});renders.push(cv);legRenders.push(legs);ac.drawImage(cv,i%4*W,Math.floor(i/4)*H);
let planted=i<4?'left':'right',mu=rotate(muzzle,helm,angle),b=bbox(cv),ls={};['leg-left','leg-right','upper'].forEach((k,j)=>ls[k]={file:'german-rifleman-walk-v2-layers.png',sourceRect:[i%4*W,(Math.floor(i/4)*3+j)*H,W,H]});
frames['german-rifleman-walk-'+i]={layers:ls,file:'german-rifleman-walk-v2.png',sourceRect:[i%4*W,Math.floor(i/4)*H,W,H],pivot,muzzle:mu,helmetCenter:helm,plantedLeg:planted,plantedFoot:foot(i,planted),feet:{left:foot(i,'left'),right:foot(i,'right')},pixelsPerUnit:P,sourceForwardRadians:0,contentBoundsAlpha32:b,status:'animation-pilot-not-approved'};
const contact=i===0||i===4;const front=foot(i,'left')[0]>=foot(i,'right')[0]?'left':'right',back=front==='left'?'right':'left';const f=foot(i,front),bf=foot(i,back);const fb=bbox(cvs[2],(x,y)=>Math.abs(y-f[1])<=30),bb=bbox(cvs[2],(x,y)=>x<600);let footBounds={left:bbox(cvs[0]),right:bbox(cvs[1])};measure.push({frame:i,contact,hipAngleDegrees:hipDeg,shoulderAngleDegrees:shoulderDeg,frontFoot:front,frontToeExtensionUnits:(footBounds[front][2]-fb[2])/P,rearHeelExtensionUnits:(bb[0]-footBounds[back][0])/P,contourMethod:'front upper alpha32 contour in boot lane +/-30px; rear global pack/back contour x<600; extensions use alpha32 leg silhouette',frontContourX:fb[2],rearContourX:bb[0],footBounds,muzzleDeviationUnits:mu.map((v,k)=>(v-muzzle[k])/P),helmetDeviationUnits:[0,0],bounds:b});}
fs.writeFileSync(path.join(out,'german-rifleman-walk-v2.png'),atlas.toBuffer('image/png'));fs.writeFileSync(path.join(out,'german-rifleman-walk-v2-layers.png'),layers.toBuffer('image/png'));
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({version:'REQUEST_004-v1',base:'german-helmet-correction-v2',layerOrder:['leg-left','leg-right','upper'],frames,animations:{'german-rifleman-walk':{frames:Object.keys(frames),cycleDistanceUnits:cycle,loop:true,drive:'distance'}}},null,2));fs.writeFileSync(path.join(out,'measurements.json'),JSON.stringify(measure,null,2));
const strip=createCanvas(1680,310),sc=strip.getContext('2d');sc.fillStyle='#59624a';sc.fillRect(0,0,1680,310);sc.font='14px sans-serif';for(let i=0;i<8;i++){let x=10+i*210,s=4/P;sc.fillStyle='#fff';sc.fillText(`${i} · ${i%4===0?'kontakt':i%2===0?'passage':'mellan'}`,x,22);sc.drawImage(renders[i],x,35,W*s,H*s);sc.drawImage(legRenders[i],x,175,W*s,H*s);let f=frames['german-rifleman-walk-'+i];for(let[k,col]of[['pivot','#ffe084'],['helmetCenter','#58c7e9'],['muzzle','#ff7161'],['plantedFoot','#f899ff']]){sc.strokeStyle=col;sc.beginPath();sc.arc(x+f[k][0]*s,35+f[k][1]*s,3,0,7);sc.stroke();}}sc.fillStyle='#fff';sc.fillText('4× · Övre rad: sammansatt. Nedre rad: enbart ben. Gul: pivot, blå: hjälm, röd: mynning, lila: stödfot.',10,300);fs.writeFileSync(path.join(out,'walk-strip-4x.png'),strip.toBuffer('image/png'));console.log(JSON.stringify(measure.filter(m=>m.contact),null,2));})();
