const fs=require('fs'),path=require('path');const{createCanvas,loadImage}=require('@napi-rs/canvas');
const out=path.resolve('outputs/REQUEST_003-v1');
const W=1254,H=700,ppu=28,cycle=28,step=cycle*ppu/8;
function foot(i,side){let q=(i+(side==='right'?4:0))%8;const y=side==='left'?285:505;let x;if(q<=4)x=780-q*step;else {const t=(q-4)/4;x=388+392*(t*t*(3-2*t));}return [x,y];}
function segment(c,im,r,a,b,width){let dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);c.save();c.translate(...a);c.rotate(Math.atan2(dy,dx));c.drawImage(im,...r,-5,-width/2,len+10,width);c.restore();}
function leg(c,im,i,side){const f=foot(i,side),sgn=side==='left'?-1:1,hip=[500,390+sgn*38],ankle=[f[0]-28,f[1]],dx=ankle[0]-hip[0],dy=ankle[1]-hip[1],d=Math.hypot(dx,dy),bend=12;const knee=[(hip[0]+ankle[0])/2-sgn*dy/d*bend,(hip[1]+ankle[1])/2+sgn*dx/d*bend];const off=side==='left'?0:550;segment(c,im,[140,370+off,460,205],hip,knee,65);segment(c,im,[580,400+off,425,175],knee,ankle,57);c.drawImage(im,990,400+off,235,170,f[0]-40,f[1]-28,80,58);}
function bounds(c){const d=c.getImageData(0,0,W,H).data;let x0=W,y0=H,x1=0,y1=0;for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(d[(y*W+x)*4+3]>=32){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x+1);y1=Math.max(y1,y+1)}return[x0,y0,x1,y1]}
(async()=>{const base=await loadImage(path.join(out,'source/reference.png')),limbs=await loadImage(path.join(out,'source/legs.png'));const atlas=createCanvas(W*4,H*2),ac=atlas.getContext('2d'),frames={},measure=[],renders=[];const ref=createCanvas(W,H),rc=ref.getContext('2d');rc.drawImage(base,0,0,W,H,0,0,W,H);const rd=rc.getImageData(0,0,W,H).data;
for(let i=0;i<8;i++){const cv=createCanvas(W,H),c=cv.getContext('2d');leg(c,limbs,i,'left');leg(c,limbs,i,'right');c.drawImage(base,0,0,W,H,0,0,W,H);renders.push(cv);ac.drawImage(cv,(i%4)*W,Math.floor(i/4)*H);let planted=i<4?'left':'right',p=foot(i,planted),b=bounds(c),d=c.getImageData(0,0,W,H).data,diff=0;for(let j=0;j<rd.length;j+=4)if(rd[j+3]===255 && (rd[j]!==d[j]||rd[j+1]!==d[j+1]||rd[j+2]!==d[j+2]))diff++;
frames['german-rifleman-walk-'+i]={file:'german-rifleman-walk.png',sourceRect:[(i%4)*W,Math.floor(i/4)*H,W,H],pivot:[600,390],muzzle:[1115,400],helmetCenter:[659,385],plantedFoot:p,plantedFootSide:planted,feet:{left:foot(i,'left'),right:foot(i,'right')},pixelsPerUnit:28,sourceForwardRadians:0,contentBoundsAlpha32:b,status:'animation-pilot-not-approved',registration:'fixed unchanged ready overlay; plantedFoot is boot sole center on ground plane'};
const prev=(i+7)%8,prevSide=prev<4?'left':'right';measure.push({frame:i,pivotDeviationUnits:[0,0],helmetDeviationUnits:[0,0],muzzleDeviationUnits:[0,0],plantedFootSide:planted,plantedFoot:p,plantedFootDeltaFromPreviousSameSideUnits:i%4===0?null:[(p[0]-foot(prev,planted)[0])/28,0],contactSwitch:i%4===0,expectedStanceDeltaUnits:[-3.5,0],sameFootWorldResidualUnits:[0,0],opaqueReferencePixelsChanged:diff,hiddenPlantedFootAllowed:true});}
fs.writeFileSync(path.join(out,'german-rifleman-walk.png'),atlas.toBuffer('image/png'));fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({version:'german-rifleman-walk-pilot-v1',base:'german-helmet-correction-v2',frames,animations:{'german-rifleman-walk':{frames:Object.keys(frames),cycleDistanceUnits:cycle,loop:true,drive:'distance'}}},null,2));fs.writeFileSync(path.join(out,'measurements.json'),JSON.stringify(measure,null,2));
const strip=createCanvas(1680,190),sc=strip.getContext('2d');sc.fillStyle='#29382b';sc.fillRect(0,0,1680,190);sc.font='14px sans-serif';for(let i=0;i<8;i++){const x=i*210+15,y=40,s=4/28;sc.fillStyle='#eee7d2';sc.fillText(`${i} · ${i===0||i===4?'kontakt':i===2||i===6?'passage':'mellan'}`,x,24);sc.drawImage(renders[i],x,y,W*s,H*s);const f=frames['german-rifleman-walk-'+i];for(const[k,col]of[['pivot','#ffe084'],['helmetCenter','#58c7e9'],['muzzle','#ff7161'],['plantedFoot','#e292ff']]){sc.strokeStyle=col;sc.beginPath();sc.arc(x+f[k][0]*s,y+f[k][1]*s,3,0,7);sc.stroke();}}sc.fillStyle='#eee7d2';sc.fillText('4× · gul: axelpunkt · blå: hjälm · röd: mynning · lila: stödfot (kan vara dold under kroppen)',15,172);fs.writeFileSync(path.join(out,'walk-strip-4x.png'),strip.toBuffer('image/png'));
console.log(JSON.stringify(measure.map(m=>({frame:m.frame,changed:m.opaqueReferencePixelsChanged,foot:m.plantedFoot}))));})();
